AmbientRun/Ambient

app/src/server/mod.rs
This fixes #47, Mithun helped me track down the cause 👍
=> fix: ServeDir should use `nest_service` instead of `route`

.github/workflows/ci.yml
#153 reported a suspicious cache usage increase.
This PR introduces a new step in the build process to output the content of the `target` directory after the build. This will help investigate if something is wrong builds after builds.
I ran multiple builds with this change and couldn't observe any file change or file increase from the same commits.
Here is an example of the new step in action: https://github.com/daniellavoie/Ambient/actions/runs/4257943674/jobs/7408628309
=> chore(ci): trace target directory content for cache troubleshooting

app/src/server/mod.rs, crates/core/src/lib.rs, crates/network/src/client.rs, crates/network/src/protocol.rs, crates/network/src/server.rs
This PR adds a new `ServerData` struct that is transmitted from the server to the client during the handshake, and is intended to store various metadata that might be relevant to the client. For now all it stores is the project name, but that can be easily changed in the future.
=> feat: update the window title with the project name - fixes #171

crates/ecs/src/entity.rs
This adds a function for asserting that all components of an `Entity` have a given attribute, panicking if any do not. Suggested by @ten3roberts in #200.
=> feat: Entity::assert_all() (resolves #200)

Cargo.lock
I noticed there were a few Dependabot warnings about `image`, so fixing that.
=> chore: run `cargo update`

crates/app/src/lib.rs, crates/debugger/src/lib.rs, crates/input/src/lib.rs, crates/ui/src/button.rs
Fixes https://github.com/AmbientRun/Ambient/issues/193.
There was a bug that prevented `hotkey_modifier` from working, the modifiers weren't being set in the keyboard event.
I decided not to implement the write_debug function in this commit since I would rather not involve it in a minor feature such as this.
=> Add Dump UI World button and remap hotkeys

Cargo.lock, Cargo.toml, crates/network/src/client.rs, crates/network/src/lib.rs, crates/network/src/protocol.rs, crates/network/src/server.rs
Newer version has a bit nicer API.
It uses custom futures instead of stream so in many cases one can get away with immutable borrows (stream needs mut) and there's no need for extra `Option` that comes from using stream's `next()` directly.
=> Update quinn to 0.9

app/src/client/mod.rs, crates/editor/src/ui/build_mode/entity_browser.rs, crates/editor/src/ui/build_mode/guide.rs, crates/editor/src/ui/build_mode/select_area.rs, crates/editor/src/ui/mod.rs, crates/editor/src/ui/terrain_mode.rs, crates/network/src/client.rs, crates/terrain/src/lib.rs, crates/ui_native/src/lib.rs, guest/rust/examples/basics/skinmesh/src/client.rs, shared_crates/element/src/hooks.rs, shared_crates/element/tests/hooks.rs, shared_crates/ui/src/button.rs, shared_crates/ui/src/editor/slider.rs, shared_crates/ui/src/editor/text_editor.rs
While doing #337, I noticed that the `Box`ing could be done automatically for the return functions in `use_spawn` and `use_effect`. Pretty straightforward ergonomics improvement.
=> refactor(element): implicitly box return fns

crates/build/src/pipelines/audio/mod.rs, crates/build/src/pipelines/mod.rs, docs/src/reference/audio.md, guest/rust/api_core/src/client/audio.rs, guest/rust/examples/games/music_sequencer/assets/pipeline.json, guest/rust/examples/games/music_sequencer/src/common.rs
Since the music sequencer uses some `wav` samples, I picked up the previous unfinished PR: https://github.com/AmbientRun/Ambient/pull/320
Now it's possible to control whether to convert `wav` or use it as is in the pipeline:
```
{
"pipeline": {
"type": "Audio",
"convert": false
}
}
```
I also documented the usage.
For `mp3`, I still feel that it's better to do the replacement in URL if the users still want to use `.mp3`, which is quite natural. There has to be a conversion anyway, so it's better to do the URL check/replacement in case of a 404 error.
`wav` is a different story: if converted, they must use `ogg`, and users should have known this if they specify it in the `pipeline.jons` by themselves.
=> Improve audio pipeline; audio format convert control

guest/rust/examples/README.md, guest/rust/examples/run_samples.bat
**Goal :** 
Help windows users build and run the examples easily using their currently installed ambient runtime
**Implementation :**
A simple win32 bat file to be executed in the the [./guest/rust/]examples/ folder (this examples folder is also the one that is zipped upon all major releases - tags)
**Execution :** 
run_samples.bat will display (v0.2.0) :
=> [win32 helper] add a bat file to help listing/building/running the examples on windows

crates/animation/src/lib.rs, crates/wasm/src/client/implementation/mod.rs, crates/wasm/src/server/implementation/mod.rs, crates/wasm/src/shared/conversion.rs, crates/wasm/src/shared/implementation/entity.rs, crates/wasm/wit/entity.wit, guest/rust/api_core/src/entity.rs, guest/rust/api_core/src/internal/bindings.rs, guest/rust/examples/basics/skinmesh/src/client.rs
Added components and system in ambient_animation:
* animation_stack: List of animation blending operations
* animation_binder_mask: List of binder string ids
* animation_binder_weights: List of masked weights (Vec<Vec<f32>>) that can be referenced by the stack
The stack uses the animation controller actions to evaluate the operations.
* AnimationActionStack: Operations (Sample, SamplePercentage, SampleAbsolute, Interpolate, Blend)
Added shared apis:
* set-animation-action-stack: Set the operations
* set-animation-binder-mask: Set the binder mask string list
* set-animation-binder-weight: Assign a list of binder weights to a slot index
Updated skinmesh example to show usage.
=> Add(feature) animation stack and masked blending

libs/physxx/src/actor.rs, libs/physxx/src/serialization.rs
Because `c_char` has different signedness on different targets (it's `u8` on aarch64 on linux) but `physx-sys` 0.8.2 uses `i8` in the generated code ([for example here](https://github.com/EmbarkStudios/physx-rs/blob/6b3a94534016270f8f6ebc665cd97ba7ce858d84/physx-sys/src/physx_generated.rs#L2069)).
=> Add casts to physxx where c_char is involved

crates/gpu/src/mesh_buffer.rs, crates/meshes/src/lib.rs, crates/text/src/lib.rs
Creating a `GpuMesh` no longer requires cloning `AssetCache`, which is a relatively expensive operation.
=> GpuMesh::from_mesh now takes &AssetCache

crates/app/src/lib.rs, crates/app/src/renderers.rs
UIRender -> UiRenderer, ExamplesRender -> MainRenderer
Rational: `er` postfix matches the rest of the codebase, and `UI` -> `Ui` is idomatic rust naming conventions. `ExamplesRender` is confusingly named as it is the `MainRenderer` and is referred to as such by some variables.
=> fix(Refactor): Refactored the Renderers

.cargo/config.toml, clippy.toml, crates/std/Cargo.toml, crates/std/src/lib.rs, crates/std/src/uncategorized/mesh.rs, crates/sys/src/native/time.rs, web/Cargo.lock
This resolves the use of Ulid calling `SystemTime::now` which is not implemented on the `wasm32-unknown-unknown` targets, as the `unknown` means that there *is* no libstd or OS, hence time is not available/implemented and just panics.
The way of getting the time is binding to JavaScript using `wasm-bindgen` and calling js `Data.now`.
In addition, the use of `Ulid::now` is now disallowed by clippy in CI
=> fix: Ulid::new() panic on web

app/Cargo.toml, app/src/cli/mod.rs, app/src/client/mod.rs, app/src/main.rs, crates/network/Cargo.toml, crates/network/src/native/client.rs, crates/network/src/native/server.rs, docs/src/user/running.md
This adds a bundled (include_bytes) certificate and key that can be disabled in production using `no_bundled_certs` (default with `production` feature.
This also allows ambient to be used with our self-signed certificates outside the ambient repo root as it would previously fail to find the cert file and key.
See the modified docs for usage 😊 
If a cert file,key, or ca is specified it will not fall back on the bundled certificates if they fail to load to avoid a false trust security vulnerability if the file is silently removed.
=> Add conditionally bundled certificates and cli certificate overrides

crates/gpu/src/mesh_buffer.rs
This subtle omission caused `mesh_buffer::update()` to effectively clear the memory of `skinned_buffer` because the updated size is always 0 bytes large.
=> Fix skinned mesh corruption (issue #378)

crates/model_import/src/gltf/mod.rs
Fixes issue with relative paths and GLTF. 
Import filepath where the name of the object contains "/" which crates subfolders and then it can't find the images
Example:
```json
{"name":"ambientCG/Fabric052/1K-JPG","base_color":"../images/0.png" }
```
The fix replaces "/" and "\\" with "-" in GLTF names for the paths but keeps the name the same, not sure if that is or will be an issue.
=> fix: gltf import filepath

crates/animation/src/lib.rs, crates/core/src/transform.rs, crates/model_import/src/fbx/model.rs
Changes:
* Removed old animation blend query
* Removed duplicate work in fbx_complex_transform query
* Refactored fbx_complex_transform
Test: 400 instances of single animated character with fbx_complex_transforms:
FPS: 20 -> 40
Overall improvement: 50~ ms / frame -> 24~ ms / frame
animation_systems 15.5 ms -> 7.5 ms
TransformSystem::run 29 ms -> > 12.5 ms
Before:
[Before](https://github.com/AmbientRun/Ambient/assets/71590722/dcd540d2-d02f-4f6c-a589-d42285a6dfe1)
After:
[After](https://github.com/AmbientRun/Ambient/assets/71590722/250c3d44-f873-4d78-8ebe-f0439b6a0d4b)
fbx_complex_transform is now about 3ms of the work, the rest is transform propagation. I would probably remove completely it unless someone has good reason for it to stay. 
Perf is not horrible but the animation sampling as a …
=> Perf: Low hanging fruit

.github/workflows/ci.yml, app/src/cli/mod.rs, app/src/cli/new_project.rs, app/src/main.rs, guest/rust/Cargo.toml
This fixes "failed to read manifest" errors when switching branches
=> fix: use explicit workspace members

guest/rust/api_core/src/entity.rs
The documentation for `mutate_component` had a default `name` instead of the name of the parameter `component`.
=> Fixed mutate_component documentation

guest/rust/api_core/src/message.rs
I was working with the guest API's `Source` struct and found the owning methods strange since they required cloning to continue using the source afterwards, so I modified them to take references instead.
=> Non-owning message source methods

.github/workflows/ci.yml, app/src/cli/new_project.rs, campfire/src/golden_images/mod.rs, crates/animation/src/lib.rs
This gets rid of the build cache for the golden-images and test-new-project-works.
Those two build steps now instead depend on the result of an earlier step.
Hopefully this will result in better cache performance
=> Re-use ambient executable in build steps

docs/src/user/setting_up_ide.md
=> Add Emacs section to IDE setup docs

CHANGELOG.md, app/src/client/wasm.rs, app/src/server/mod.rs, crates/animation/src/player.rs, crates/app/src/lib.rs, crates/core/src/lib.rs, crates/network/src/native/server.rs, crates/network/src/server.rs, crates/physics/examples/physics.rs, crates/physics/src/helpers.rs, crates/physics/src/lib.rs, crates/sys/src/native/time.rs, crates/sys/src/wasm/time.rs, guest/rust/api_core/src/animation.rs, guest/rust/api_core/src/global/runtime.rs, guest/rust/clippy.toml, guest/rust/examples/basics/asset_loading/src/server.rs, guest/rust/examples/basics/async/src/common.rs, guest/rust/examples/basics/clientside/src/client.rs, guest/rust/examples/games/minigolf/src/server.rs, guest/rust/examples/games/music_sequencer/src/client.rs, guest/rust/examples/ui/clock/src/client.rs, guest/rust/examples/ui/todo/src/server.rs, shared_crates/schema/src/schema/app_.toml
The use of the UNIX epoch for the existing `time()` function resulted in `as_secs_f32` on the guest suffering from integer rounding of f32s (as the current Unix timestamp is past 2^24-1). To avoid this, I've split `time` into `absolute_game_time` and `absolute_epoch_time`, so that users can know what to expect and to pick the one that's more appropriate for their application.
Along the way, I made these other fixes: 
- Be more consistent about the use of `Instant` vs `SystemTime` for ticking
- Use a fixed server tick across the board
- Unify time handling logic across client and server
=> Split `time` into `absolute_game_time` and `absolute_epoch_time`

app/src/cli/new_project.rs, crates/network/src/proto/mod.rs
https://github.com/AmbientRun/Ambient/issues/559
`--abbrev=10` - use at least 10 characters from commit hash (should we use the full 40?)
`--always` - always show something, that is at least a commit hash (so it works for commits that don't have any tags in their path to the root)
`--long` - always put all fields, otherwise it will skip the commit hash if the commit is tagged
=> Fix version formatting in network crate

Cargo.lock, crates/ecs/Cargo.toml, crates/ecs/src/stream.rs, crates/ecs/tests/streaming.rs, crates/network/src/native/server.rs, crates/network/src/native/webtransport.rs, crates/network/src/proto/server.rs, crates/network/src/rpc.rs, crates/network/src/server.rs
Quick fix for diff queue build up when sending diffs is delayed (due to bad network conditions).
Note that although it tries to be frugal on clones and allocations it still scales linearly with the number of connected players. It shouldn't be a problem for now but I would like to put some more work on our diff streaming in seperate PRs.
Because of the above it adds 2 temporary `WorldDiff` variants/flavours:
- `WorldDiffView<'a>` - storing a selection of changes
- `FrozenWorldDiff` - immutable `WorldDiff` that is cheap to share via `clone` (kind of like `Bytes`)
Which all serialise the same way (being just a collection of `WorldChange`).
=> Merge pending diffs before sending

app/src/cli/assets.rs, app/src/cli/build.rs, app/src/cli/client.rs, app/src/cli/deploy.rs, app/src/cli/mod.rs, app/src/cli/new_project.rs, app/src/cli/project_path.rs, app/src/cli/server.rs, app/src/client/mod.rs, app/src/main.rs, app/src/server/mod.rs, app/src/shared/certs.rs, app/src/shared/mod.rs, campfire/src/golden_images/mod.rs, crates/deploy/src/lib.rs
As suggested by @ten3roberts - breaking up the Ambient native `main` so that it's easier to see what each command does. This fixes #683.
To-do:
- Clean up the resulting functions (I just went at it with R-A to get the loose outline of it in place)
- See if we can unify this with the web
=> Clean up Ambient native entrypoint

app/src/cli/build.rs, app/src/cli/client.rs, app/src/cli/deploy.rs, app/src/cli/project_path.rs, app/src/cli/server.rs, app/src/main.rs, app/src/server/mod.rs, crates/deploy/src/lib.rs
This removes the use of build/ for deployed embers, making the flow much simpler. For corresponding backend change, see api_server/v0.5.7.
=> feat(app): simplify host flow

crates/ecs/src/stream.rs, crates/native_std/src/uncategorized/mod.rs, crates/native_std/src/uncategorized/size_histogram.rs, crates/network/src/diff_serialization.rs, crates/network/src/native/client.rs, crates/network/src/proto/client.rs, crates/network/src/proto/server.rs, crates/network/src/stream.rs, crates/network/src/web/client.rs
- indexes paths and only sends u32 index (plus newly encountered paths) - https://github.com/AmbientRun/Ambient/issues/627
- serializes EntityId in binary format - https://github.com/AmbientRun/Ambient/issues/628
- switches to var int encoding to save space on encoded lengths and other small integers
Longer test with afps:
```
old:
1KB:   976
2KB:  1156
4KB:   385
8KB:  1164
16KB:  1783
32KB:   680
64KB:    36
Average: 10KB
new:
1KB:  2352
2KB:  1064
4KB:  1610
8KB:  1126
16KB:    28
Average: 3KB
```
afps after destroying boxes and rejoining to see difference on initial world diff:
```
old:
1KB:   259
2KB:   742
4KB:    85
8KB:    79
16KB:   132
32KB:    79
64KB:     3
128KB:     0
256KB:     0
512KB:     0
1024KB:     1
Average: 6KB
new:
1KB:  1061
2KB:    82
4KB:   134
8KB:   100
16KB: …
```
=> Optimize serialized diff size

Cargo.lock, crates/network/src/native/mod.rs, guest/rust/Cargo.lock, web/Cargo.lock
Quick test seems to indicate this works fine, but making it a PR just so that @ten3roberts can verify.
=> chore: update rustls to fix dependabot alerts

app/src/main.rs, docs/src/SUMMARY.md, docs/src/reference/distributing.md
This makes it possible to set cli args with a `launch.json` file (which makes it possible to create native desktop distributions of a game).
=> Launch.json + distributing docs

crates/network/src/diff_serialization.rs, web/Cargo.lock, web/Cargo.toml, web/client/Cargo.toml, web/client/src/lib.rs, web/www/src/main.ts
Fixes `Error: no such component: 336` seen on the web client
=> fix(web): semantic packages

.github/workflows/build-nightly.yml, .github/workflows/ci.yml, .github/workflows/deploy-examples.yml, .github/workflows/deploy-web.yml
At least until https://github.com/Swatinem/rust-cache/issues/167 is addressed
Note that there's no need to switch caches between main and test configurations because cargo cache already handles cache fallbacks with restore-keys
=> Change CI cache to cargo-cache

crates/ecs/src/generated.rs, crates/wasm/src/server/mod.rs, crates/wasm/src/shared/message.rs, crates/wasm/src/shared/mod.rs, shared_crates/package/src/message.rs, shared_crates/package_macro_common/src/messages.rs, shared_crates/package_rt/src/message_serde.rs, shared_crates/package_semantic/src/message.rs
Some messages, while sent by the runtime, need to be able to be sent by packages, too. This primarily concerns the UI.
To enable this, I've added `as_module_message` as a field for messages in packages, so that you can set `as_module_message = true` and both the host and the guest will generate them as `ModuleMessage`s instead.
=> Add `as_module_message` for Ambient-defined messages

campfire/src/install.rs, crates/world_audio/src/systems.rs
This refactors the code to remove the unwraps by encoding assumptions and by early-exiting. I've also taken advantage of #845 to remove all of the children-sync code.
=> fix #831 - remove unwraps from world audio systems

Cargo.lock, Cargo.toml, app/Cargo.toml, app/src/main.rs, crates/git_rev/Cargo.toml, crates/git_rev/README.md, crates/git_rev/build.rs, crates/git_rev/src/lib.rs, crates/native_std/Cargo.toml, crates/native_std/src/lib.rs
https://github.com/AmbientRun/Ambient/issues/835
This works almost like the git-version macro, the main difference being: it keeps only the `.git/logs/HEAD` as a dependency for rebuilds while git-version also tracks `.git/index`.
=> Fix excessive rebuilds

campfire/src/golden_images/mod.rs, campfire/src/package.rs, guest/rust/.gitignore, guest/rust/Cargo.lock, guest/rust/Cargo.toml, guest/rust/packages/games/tangent/Cargo.toml, guest/rust/packages/games/tangent/ambient.toml, guest/rust/packages/games/tangent/core/ambient.toml, guest/rust/packages/games/tangent/core/src/client.rs, guest/rust/packages/games/tangent/mods/scene/ambient.toml, guest/rust/packages/games/tangent/src/server.rs, guest/rust/packages/tools/package_manager/Cargo.toml, guest/rust/packages/tools/package_manager/ambient.toml, guest/rust/packages/tools/package_manager/src/client/package_manager.rs, guest/rust/packages/tools/package_manager/src/server/package_manager.rs, guest/rust/packages/tools/package_manager/src/shared.rs, shared_crates/ui/src/tabs.rs
Revises the package manager to act double-duty as a mod manager by specifying the `mod_manager_for` component on its package entity.
There are a few TODOs, but it works without fixing them:
- Filter what's relevant to us using the API, not by grabbing all of it and filtering there
- Add `content` and `playable_for` to the package components so we can figure out if a local package is relevant without having to ask the server about it
Notably, this does not make any changes to Ambient (outside of making Campfire deploy mods) - this should mean it's compatible with today's nightly.
=> Mod manager

app/src/cli/deploy.rs, app/src/cli/mod.rs, crates/deploy/src/lib.rs, guest/rust/Cargo.lock, guest/rust/packages/tools/package_manager/Cargo.toml, guest/rust/packages/tools/package_manager/src/server/package_load.rs, guest/rust/packages/tools/package_manager/src/server/package_manager.rs, shared_crates/package/src/manifest.rs, shared_crates/shared_types/src/lib.rs, shared_crates/shared_types/src/urls.rs
Adds URL helpers to reduce duplication and to help with moving the URLs when required.
Also fixes:
- web URL in deployment
- using the proper API request for package manager
=> feat: add url helpers

shared_crates/package_semantic/src/lib.rs, shared_crates/package_semantic/src/package.rs, shared_crates/package_semantic/src/util.rs
The previous method for detecting conflicts would do detection in resolution, which would leave the semantic in an unrecoverable state (once you had an invalid package in there, you could never add another package again).
This switches a lot of the semantic code over to using `thiserror` to provide better errors, and then moves the conflict check to addition.
However, this doesn't solve the full problem - if a dependency fails to be added, the package that added it will remain, which will lead to strange behaviour. I'll open an issue for that.
=> Semantic: frontload package conflict errors

.cargo/config.toml, campfire/src/web/browser.rs
It was after I did this that I realised Chrome stable on Linux doesn't support WebGPU, which meant this wasn't of much use anyway (without switching to canary + adding some flags). Oh well.
=> fix(campfire): build on linux

.cargo/config.toml, Cargo.lock, Cargo.toml, campfire/Cargo.toml, campfire/src/web/browser.rs, campfire/src/web/mod.rs, recipes.json, web/README.md
Really didn't want to go through the hassle of getting OpenSSL to work on Windows, so I just replaced the logic with Rust equivalents. My Chrome starts up and connects to my 127.0.0.1 server OK. Need to test on the other platforms.
=> feat(campfire): replace OpenSSL with Rust deps

Cargo.lock, app/Cargo.toml, app/src/client/mod.rs, crates/client_shared/Cargo.toml, crates/client_shared/src/lib.rs, crates/client_shared/src/util.rs, crates/settings/src/general.rs, docs/src/tutorials/game/6_ui.md, guest/rust/packages/games/afps/core/fpsui/src/client.rs, guest/rust/packages/games/tangent/core/src/client.rs, guest/rust/packages/games/tangent/mods/ui_class_selection/src/client.rs, guest/rust/packages/games/tangent/mods/ui_holohud/src/client.rs, guest/rust/packages/tools/editor/src/client.rs, guest/rust/packages/tools/package_manager/src/client/package_manager.rs, shared_crates/element/src/hooks.rs, shared_crates/ui/src/layout.rs, shared_crates/ui/src/text.rs, web/Cargo.lock, web/client/src/app.rs
Have been working on Tangent in the background, but pulled these fixes/changes out from my branch as they're generally relevant.
- You can now set `general.user_id` for the native client's settings.
- `Text3D` lets you easily position text in space. I'm not sure about its interface quite yet, but it does make it much easier.
- `LayoutFreeCenter` offers a solution to the problem of centering 3D text (#112). It's not the best solution - ideally the mesh itself would be centered at the point - but it works.
- Literally no use of `use_entity_component` uses the setter. I've removed it to make it simpler and to make it clearer that you can't manipulate the server with it.
- The desktop and web clients now generate a nice AdjectiveAnimal name if you don't have one specified. After this goes in, …
=> Misc fixes

.github/workflows/ci.yml, guest/rust/golden-image-manifest.toml
So that tests can run for #945
=> Disable unity GI test on CI

crates/physics/src/physx.rs
This PR addresses #803
This PR adds a new query to the physx system to update entities that have `physics_shape` components and their `local_to_world` changes. This covers the case where an entity is the child of a hierarchy and has a physics collider attached. The child entities may not change its `translation` or `rotation` components but its parents will and the child needs to update its collider state accordingly.
Heres an example gif with a `visualize_collider` component. The collider is generate from the asset pipeline and the ship model is a child of a parent entity that handles all the movement and rotation.
I need feedback and guidance on this. I basically copied this from the `query((translation().changed(), rotation().changed())).incl(physics_shape());` query implementation. …
=> Fix #803 child collision volumes

Cargo.lock, Cargo.toml, crates/asset_cache/src/lib.rs, crates/ecs/Cargo.toml, crates/ecs/src/attributes.rs, crates/ecs/src/component.rs, crates/ecs/src/component_traits.rs, crates/network/Cargo.toml, crates/network/src/client.rs, crates/renderer/Cargo.toml, crates/renderer/src/lib.rs, shared_crates/element/src/hooks.rs, shared_crates/element/src/lib.rs
NOTE: as the new `as-any` version implements `Downcast` directly for everything that could support it, name resolution changes a bit and requires more explicit dereferences.
* `cargo fmt --check` passes
* `cargo test --all` passes
=> bump as-any; get rid of downcast-rs usage

crates/input/src/lib.rs, shared_crates/ui/src/editor/text_editor.rs
One half of #951. Looking into the other half.
This PR ignores control characters in `WindowKeyboardCharacter`, so that `TextEditor` will always use `WindowKeyboardInput` for its control behaviour.
=> fix(input): use KeyboardInput to unify flow

crates/gizmos/src/render.rs, crates/gpu/src/gpu_run.rs, crates/gpu/src/mesh_buffer.rs, crates/gpu/src/typed_buffer.rs, crates/gpu_ecs/src/lib.rs, crates/gpu_ecs/src/update.rs, crates/naturals/src/compute.rs, crates/rect/src/lib.rs, crates/renderer/src/collect.rs, crates/renderer/src/culling.rs, crates/renderer/src/shadow_renderer.rs, crates/renderer/src/skinning.rs, crates/renderer/src/transparent_renderer.rs, crates/sky/src/lib.rs
Just addressing the biggest offenders in time for 0.3.
String labels cross the js boundary and make calls to wgpu more expensive.
Ideally we would wrap the wgpu calls so that labels would be elided in non dev builds.
The downside is we lose some debug information until we find a more general solution.
=> Reduce string usage in the renderer to improve performance

Cargo.lock, crates/app/src/lib.rs, crates/ecs/src/generated.rs, crates/input/Cargo.toml, crates/input/src/lib.rs, crates/wasm/src/client/implementation/specific.rs, guest/rust/api_core/src/internal/generated.rs, guest/rust/packages/std/hide_cursor/src/client.rs, schema/schema/ambient.toml, web/Cargo.lock
`Confined` isn't supported on the web, but `Locked` is. Fixing that made cursor locking work, but then there were issues where you'd release the lock in the browser but the game still thought you were locked. Fixed this by propagating the window-lock state to the guest.
@ten3roberts at some point you may want to check my use of `add_event_listener` here, I have no idea if it gets cleaned up
=> fix #894 - web cursor locking

.github/workflows/deploy-packages.yml, .github/workflows/deploy-server.yml, .github/workflows/deploy-web.yml, .github/workflows/publish-api.yml, .github/workflows/release-version.yml, .github/workflows/tag-internal.yml
I *think* this should work, but I'm going to get a second pair of eyes before I merge it.
The idea is that `release-version` always kicks off the other workflows, and `tag-nightly` sets up the environment for `release-version` and then calls it. This should lead to consistent behaviour when cutting a release.
=> feat(ci): release-version drive other workflows

crates/water/src/water.wgsl, web/client/src/app.rs
The textureSampleLevel is buggy on wgpu and does not accept a int for depth comparison.
Is there a specific reason the compare*Level* was used, rather than a normal texture sample. Did it fix a specific bug in the past? The git log goes back to the `Init` squash.
=> fix(web): water using the same trick as the atmosphere

campfire/src/web/browser.rs, campfire/src/web/mod.rs
I just want to be able to run: `cargo cf web open-browser -a 'Google Chrome Canary'` on my mac. Not sure how much it makes sense for other OSes. Tested on:
Also fixes URL passing on macOS.
=> Allow for Chrome app selection in `campfire web open-browser`

campfire/src/join.rs, campfire/src/package.rs, campfire/src/util.rs
The `production` feature flag is needed to enable `assimp`, which is needed for to deploy the assimp example. It's only adding that feature flag for deploy-all now though.
It feels like deploy-all should be moved to `ambient` runtime instead though, that that the ci job should just use the latest ambient runtime? (Instead of building at again)
=> Use --feature production on cf deploy-all

app/src/cli/package/new.rs, crates/native_std/src/lib.rs
https://github.com/AmbientRun/Ambient/issues/1033
Not sure if we should include release candidates in this too - waiting for opinions.
Tested with `cargo cf release update-version 0.3.1` followed by `cargo run -- new ...`.
=> Fix `ambient_api` dep version in new project

crates/network/src/web/client.rs
@pierd do we still need this soft server start, or is probing and initialization order working correctly now?
=> Remove temporary sleep for server startup

crates/pipeline_types/src/lib.rs
I needed to expose these values to use them in a custom build.rs example:
``` rust
use ambient_pipeline_types::{
MaterialsImporter, MaterialsPipeline, ModelImporter, ModelsPipeline, Pipeline,
PipelinePbrMaterial, PipelineProcessor, PipelinesFile,
};
fn main() {
PipelinesFile {
pipelines: vec![
Pipeline {
processor: PipelineProcessor::Models(ModelsPipeline {
importer: ModelImporter::Regular,
..Default::default()
}),
sources: vec!["ships/*.glb".to_string()],
tags: vec![],
categories: vec![],
},
Pipeline {
processor: PipelineProcessor::Models(ModelsPipeline {
importer: ModelImporter::Regular,
..Default::default()
}),
sources: vec!["maps/*.glb".to_string()],
tags: vec![],
categories: vec![],
},
Pipeline {
processor: PipelineProcessor::Materials(MaterialsPipeline {
importer: …
```
=> Export MaterialsImporter and PipelinePbrMaterial from pipeline_types

crates/renderer/src/renderer.rs
This gets rid of black outlines on objects that are solid but are using alpha cutoff. 
Potentially addressing one of the issues for #983
=> Make alpha always 1 for solid objects

crates/ecs/src/generated.rs, crates/physics/src/lib.rs, crates/wasm/src/server/mod.rs, guest/rust/api_core/src/internal/generated.rs, libs/physxx/src/scene.rs, schema/schema/ambient.toml
This Pr updates the physics pipeline to expose collision contact points and normals. Still testing this but opening it up for review and discussion.
=> Add support for collision contact points and normals

app/src/cli/package/mod.rs
Seems this cli help text is incorrect and code actually defaults to `8999` at:
https://github.com/AmbientRun/Ambient/blob/256172a79d203f0669dce6bf5c9a7fab0cbab5d1/app/src/server/mod.rs#L303
=> fix cli http_interface_port consistency

Cargo.lock, Cargo.toml, app/Cargo.toml, app/src/cli/package/mod.rs, app/src/server/mod.rs, crates/native_std/src/lib.rs
- `--use-https` options to serve http content with TLS so that it conforms to Secure context restrictions (https://github.com/AmbientRun/Ambient/issues/1143)
- simple embedded web client page hosting when running a released version (https://github.com/AmbientRun/Ambient/issues/1133)
=> Make it easier to self host Ambient servers

guest/rust/packages/std/nameplates/ambient.toml, guest/rust/packages/std/nameplates/src/client.rs
This PR attempts to add a parameter to t he `nameplates` package that does not render the name plate for the local player. 
This doesn't currently work. I'm opening PR for discussion: 
In my game code I attempt to use with:
``` rust
spawn_query((is_player(), user_id())).bind(move |players| {
for (player_id, (_, uid)) in players {
// First, we check if this player is the "local" player, and only then do we attach a camera
if uid == entity::get_component(entity::resources(), local_user_id()).unwrap() {
// hide the nameplate for local player
println!("adding hide to {:?}", player_id);
entity::add_component(player_id, packages::nameplates::components::hide(), ());
p
...
```
However this doesn't work as the `nameplate` package is executed before this `hide` component gets added.
initially …
=> Add hide component for nameplates

.github/workflows/ci.yml, .github/workflows/release-version.yml
=> Windows code signing

campfire/src/util.rs, guest/rust/examples/assets/unity/download.sh
Since the ~11th, package nightlies have not been deployed, and nobody was aware of them. This is a combination of two issues:
1) Failures in Campfire-spawned Ambient commands did not cause Campfire to exit with a non-zero status code, resulting in a silent failure
2) Our download script for the Unity assets was constructing URLs with double slashes (i.e. `BASE//path` instead of `BASE/path`), resulting in invalid assets being downloaded. My guess is that DO stopped accepting double-slashed URLs?
This PR fixes both of these issues, and should hopefully allow for package deployment to go out as per normal.
=> Fix package deployment failure

Cargo.lock, Cargo.toml, crates/build/Cargo.toml, crates/build/src/pipelines/audio/mod.rs
Even though OptiVorbis was deemed appropriate for the sound build pipeline of Ambient in #619, its inclusion was later reverted in #751 due to a significant impact in compile times for a transitive dependency.
The good news is that, at long last, a new version of OptiVorbis is here, with refactored internals that got rid of the troublesome dependencies! Several other changes have also been made, which can be read [here](https://github.com/OptiVorbis/OptiVorbis/blob/master/CHANGELOG.md#020---2023-12-11).
While at it, I've also updated the dependency on `vorbis_rs`. This new version of `vorbis_rs` brings a new builder for instantiating encoders as I initially discussed with @marceline-cramer in https://github.com/ComunidadAylas/vorbis-rs/pull/9, and other minor fixes and QoL changes you can …
=> feat(build): bring back OptiVorbis

.github/workflows/deploy-packages.yml
Before #1225, nightly builds would create a PR that consisted of three commits:
- Update the version of Ambient to the desired version
- Deploy all packages, making a commit with the new deployment IDs
- Revert the version back to `-dev`, except for the deployed packages
However, after that PR, deployment IDs are no longer used; instead, package versions are used, which are set by the first commit (`update-version`). This means that the second commit was empty, causing failures.
To fix this, I've removed the second commit (as it's implied by the first commit), as well as the corresponding step for tagged builds (actually not sure about this one, following up with Kuba)
=> fix(ci): remove deploy-packages empty commits
