AmbientRun/Ambient

crates/model_import/src/model_crate.rs, crates/physics/src/physx.rs
=> fix: PhysX mesh weld tolerance was too high, removed outdated comment

.github/workflows/book.yml, .github/workflows/ci.yml, .github/workflows/release.yml
Tested running a server in WSL2 Ubuntu 20.04 with a build using this CI (in my fork) with no issues.
=> feat(ci): build on ubuntu 20.04 - fix #149

crates/gpu/src/gpu.rs
=> chore: fix typo in gpu.rs

app/src/cli/new_project.rs
Fixes https://github.com/AmbientRun/Ambient/issues/214
=> Dynamic path to local api when creating projects in examples directory

crates/element/src/hooks.rs, crates/guest_bridge/src/guest.rs, guest/rust/api/src/global/runtime.rs, guest/rust/api/src/internal/component/query.rs, guest/rust/api/src/internal/executor.rs
Fixes #225
@philpax This should work right?
=> Handles for "on" and "once"

app/src/cli/new_project_template/src/client.rs, app/src/cli/new_project_template/src/server.rs
Looks like this was missed in https://github.com/AmbientRun/Ambient/commit/abe3e624c12cc463da2862d076070eedac249421
=> Use ResultEmpty and OkEmpty in new_project_template

.github/workflows/ci.yml
Making sure that #260 won't be necessary next time 😅
=> feat(ci): test new project works

.github/workflows/ci.yml
Hopefully this resolves the issues with running out of space on Windows
=> feat(ci): split out new project test

app/src/cli/new_project_template/.gitignore, crates/project_native/src/lib.rs, guest/rust/.vscode/launch.json, guest/rust/examples/basics/first_person_camera/ambient.toml, guest/rust/examples/basics/messaging/ambient.toml, guest/rust/examples/basics/physics/ambient.toml, guest/rust/examples/basics/screen_ray/ambient.toml, guest/rust/examples/basics/third_person_camera/ambient.toml, guest/rust/examples/games/minigolf/ambient.toml, guest/rust/examples/games/pong/ambient.toml, guest/rust/examples/games/tictactoe/ambient.toml, guest/rust/examples/ui/todo/ambient.toml, shared_crates/project/src/component.rs, shared_crates/project/src/concept.rs, shared_crates/project/src/manifest.rs, shared_crates/project/src/message.rs, shared_crates/project_macro_common/src/component.rs, shared_crates/project_macro_common/src/concept.rs, shared_crates/project_macro_common/src/message.rs, shared_crates/project_macro_common/src/tests.rs, shared_crates/project_macro_common/src/util.rs
Allows components, messages, namespaces and concepts to not have descriptions
=> Optional descriptions in project manifest

docs/src/reference/common_pitfalls.md
Adds information at Ambient/docs/src/reference/common_pitfalls.md about how to fix the os error 10060.
=> Added information about fix to os error 10060

crates/renderer/src/lod.rs, shared_crates/element/src/element_config.rs, shared_crates/element/src/hooks.rs, shared_crates/element/src/lib.rs, shared_crates/element/src/standard.rs, shared_crates/element/src/tree.rs, shared_crates/ui/src/lib.rs
Partially complete, need to finish this
=> Document Element

CHANGELOG.md, ambient.toml, app/src/cli/new_project_template/src/server.rs, crates/cameras/src/lib.rs, crates/cameras/src/spherical.rs, crates/core/src/transform.rs, guest/rust/examples/basics/asset_loading/src/server.rs, guest/rust/examples/basics/clientside/src/client.rs, guest/rust/examples/basics/fog/src/client.rs, guest/rust/examples/basics/image/src/server.rs, guest/rust/examples/basics/multiplayer/src/server.rs, guest/rust/examples/basics/physics/src/server.rs, guest/rust/examples/basics/primitives/src/server.rs, guest/rust/examples/basics/raw_text/src/server.rs, guest/rust/examples/basics/screen_ray/src/client.rs, guest/rust/examples/basics/skinmesh/src/client.rs, guest/rust/examples/basics/sun/src/server.rs, guest/rust/examples/basics/third_person_camera/src/client.rs, guest/rust/examples/basics/transparency/src/client.rs, guest/rust/examples/games/tictactoe/src/server.rs
=> Rename lookat_center to lookat_target

guest/rust/examples/games/music_sequencer/ambient.toml, guest/rust/examples/games/music_sequencer/src/client.rs, guest/rust/examples/games/music_sequencer/src/common.rs, guest/rust/examples/games/music_sequencer/src/server.rs
use the ecs practice; avoid using Arc and Mutex for customised database.
use Rect in the Button;
use Vec of u32 for note_selection rather than Vec of Vec4
=> fix music sequencer

Cargo.lock, Cargo.toml, Dockerfile, campfire/Cargo.toml, campfire/src/release.rs, docs/src/user/installing.md, guest/rust/Cargo.toml, web/Cargo.toml
=> Add campfire release::check

crates/build/src/pipelines/models/unity.rs, crates/gpu/src/mesh_buffer.rs, crates/meshes/src/capsule.rs, crates/meshes/src/cuboid.rs, crates/meshes/src/grid.rs, crates/meshes/src/lib.rs, crates/meshes/src/pyramid.rs, crates/meshes/src/torus.rs, crates/meshes/src/uvsphere.rs, crates/model_import/src/assimp.rs, crates/model_import/src/fbx/mesh.rs, crates/model_import/src/gltf/mod.rs, crates/model_import/src/model_crate.rs, crates/physics/src/intersection.rs, crates/std/src/uncategorized/mesh.rs, crates/text/src/lib.rs, crates/ui_native/src/graph.rs, libs/unity_parser/src/asset.rs
The rest of the code base asserts their existence so it makes sense to enforce it at import-time.
=> Mesh position and index buffers are now required to exist

.gitignore, Cargo.toml, app/src/cli/mod.rs, app/src/main.rs, app/src/server/mod.rs, crates/network/Cargo.toml, crates/network/src/lib.rs
This allows flags *before* subcommands like run which apply for every subcommand
=> feat: non-subcommand specific flag support

crates/animation/src/lib.rs, crates/gpu/src/mipmap.rs, crates/gpu/src/texture.rs, crates/gpu/src/texture_loaders.rs, crates/renderer/examples/custom_material/main.rs, crates/renderer/examples/pbr.rs, crates/renderer/examples/renderer_update.rs, crates/renderer/examples/texture.rs, crates/renderer/examples/translucency.rs, crates/renderer/src/materials/flat_material.rs, crates/renderer/src/materials/pbr_material.rs, crates/terrain/src/gather_spread.rs, crates/terrain/src/lib.rs, crates/ui_native/src/graph.rs, crates/ui_native/src/image.rs, crates/wasm/src/client/implementation/specific.rs, crates/wasm/src/shared/implementation/asset.rs
This commit focuses on textures and material functions.
=> More functions now borrow `AssetCache` instead of taking ownership

CONTRIBUTING.md, README.md, docs/src/community/contributing.md
Just updating the contributing docs to clarify the host/guest relationship
=> docs: clarify contribution

crates/renderer/examples/pbr.rs, crates/renderer/examples/texture.rs, crates/renderer/src/materials/pbr_material.rs, crates/ui_native/src/image.rs, crates/wasm/src/client/implementation/specific.rs
Reverts some changes into PbrMaterialConfig caused by PR #391.
=> Fix decals

Cargo.lock, Cargo.toml, guest/rust/Cargo.lock, guest/rust/Cargo.toml, web/Cargo.toml
=> bump crate: glam 0.24

Cargo.lock, Cargo.toml, crates/meshes/src/capsule.rs, crates/meshes/src/cuboid.rs, crates/meshes/src/grid.rs, crates/meshes/src/lib.rs, crates/meshes/src/pyramid.rs, crates/meshes/src/torus.rs, crates/meshes/src/uvsphere.rs, crates/model_import/src/fbx/mesh.rs, crates/model_import/src/gltf/mod.rs, crates/std/Cargo.toml, crates/std/src/uncategorized/mesh.rs
Implements https://github.com/AmbientRun/Ambient/issues/21.
=> Replace tangent generator with `mikktspace`

Cargo.lock, Cargo.toml, crates/network/Cargo.toml, crates/network/src/client.rs
=> Update quinn, rustls and ambient_proxy

Cargo.lock, Cargo.toml, app/Cargo.toml, app/src/main.rs, crates/network/src/native/server.rs
Tested with self signed certs and with production certs.
=> Add support for PEM certificate chains

app/src/server/mod.rs
https://github.com/AmbientRun/Ambient/issues/499
=> Fix public_host calculation

Cargo.lock, app/src/client/mod.rs, crates/ecs_editor/Cargo.toml, crates/ecs_editor/src/lib.rs, shared_crates/schema/src/schema/ecs.toml, web/Cargo.lock
https://github.com/AmbientRun/Ambient/assets/35621141/e7bd3ff2-78f0-4dbe-9376-2027b7f46c62
=> Add filter to debugger

crates/network/src/native/client.rs, crates/network/src/native/server.rs, crates/network/src/native/webtransport.rs
Making this a PR in case there is any log that needs to stay
=> chore: reduce logging

CHANGELOG.md, crates/animation/src/player.rs, crates/core/src/lib.rs, guest/rust/Cargo.lock, guest/rust/api_core/src/animation.rs, guest/rust/api_core/src/global/runtime.rs, guest/rust/examples/basics/asset_loading/src/server.rs, guest/rust/examples/basics/async/src/common.rs, guest/rust/examples/basics/clientside/src/client.rs, guest/rust/examples/games/minigolf/src/server.rs, guest/rust/examples/games/music_sequencer/src/client.rs, guest/rust/examples/games/pong/src/client.rs, guest/rust/examples/ui/clock/src/client.rs, guest/rust/examples/ui/todo/src/server.rs, shared_crates/schema/src/schema/app_.toml
Ever make a change and then realize two minutes later that you could have made a better change?
=> fix(api): drop absolute_ prefix from time fn/comp

guest/rust/Cargo.lock, guest/rust/examples/basics/instancing/Cargo.toml, guest/rust/examples/basics/instancing/ambient.toml
=> Rename instancing -> ambient_example_instancing

docs/src/user/installing.md
=> fix(docs): install instructions

Cargo.lock, Cargo.toml, web/Cargo.lock, web/Cargo.toml
=> chore: update more packages

crates/editor/src/ui/mod.rs, guest/rust/examples/ui/clock/src/client.rs, shared_crates/ui/src/editor/collections.rs, shared_crates/ui/src/editor/primitives.rs, shared_crates/ui/src/editor/text_editor.rs, shared_crates/ui/src/layout.rs, shared_crates/ui/src/lib.rs, shared_crates/ui/src/prelude.rs
Just letting the CI check I didn't break anything here
=> feat(ui): move more to HooksExt

.github/workflows/ci.yml, app/src/client/wasm.rs, campfire/src/golden_images/mod.rs
The first-person camera example is failing because it segfaults. It's hard to debug that locally, so I'm going to try a bunch of random fixes first before I do anything more complicated.
=> Fix golden images maybe

Cargo.lock, app/src/client/wasm.rs, crates/world_audio/src/sounds.rs, crates/world_audio/src/systems.rs, guest/rust/examples/ui/audio_ctrl/src/client.rs
This should fix https://github.com/AmbientRun/Ambient/issues/587
=> support audio looping and fix some audio bugs

Cargo.lock, Cargo.toml, crates/build/Cargo.toml, crates/build/src/pipelines/audio/mod.rs
[OptiVorbis](https://github.com/OptiVorbis/OptiVorbis) is a novel Ogg Vorbis file optimization tool that slightly reduces their size without any compromise on audio quality, portability, or runtime decoding performance. It executes much faster than most generic compression programs, so it shouldn't affect build times too much.
OptiVorbis has been thoroughly tested, and its documentation explains in detail how it works. Given that audio assets can take a substantial chunk of the total game size, I think OptiVorbis is a great fit for Ambient and has the potential to substantially improve the distribution experience for players.
Disclaimer: I am the author of OptiVorbis. Thanks for using the `vorbis_rs` crate, which I also wrote, and which made me aware of this cool game engine project!
=> feat: optimize files generated by audio build pipeline with OptiVorbis

CHANGELOG.md, app/Cargo.toml, app/src/cli/mod.rs, app/src/main.rs, crates/build/Cargo.toml, crates/build/src/pipelines/importer.rs, crates/build/src/pipelines/mod.rs, guest/rust/Cargo.lock
@ten3roberts I have to change a little bit on your previous implementation on Migrating. I hope it makes sense.
=> add import for cli assets command

crates/network/src/lib.rs, crates/network/src/proto/client.rs, crates/network/src/proto/mod.rs, crates/network/src/serialization.rs
For situations like this: https://github.com/AmbientRun/Ambient/issues/692
=> Handle external components deserialization issues gracefully

app/src/server/mod.rs, crates/build/src/lib.rs, crates/native_std/src/lib.rs
for https://github.com/AmbientRun/Ambient/issues/684
=> Add `/info` endpoint

.github/workflows/ci.yml
Test how much it improves CI build times
=> Run CI build job in debug mode

guest/rust/Cargo.lock, web/Cargo.lock
=> chore: update reqwest to remove webpki dependency

app/src/cli/mod.rs, app/src/cli/server.rs, app/src/main.rs, app/src/server/mod.rs, crates/network/src/native/server.rs
I've noticed that we already have one. Fixing it and exposing as an argument so that it can be easily used on the backend.
=> Expose inactivity shutdown

.github/workflows/build-nightly.yml, .github/workflows/release.yml, Cargo.toml, app/Cargo.toml, app/src/main.rs, crates/settings/src/general.rs, crates/settings/src/lib.rs, docs/src/SUMMARY.md, docs/src/user/settings.md
Upload debug symbols for nightly builds.
Add documentation for Ambient settings.
=> Add support for Sentry native crashes and allow users to disable it or use their own DSN with client settings.

shared_crates/package_macro_common/src/context.rs, shared_crates/package_semantic/src/attribute.rs, shared_crates/package_semantic/src/component.rs, shared_crates/package_semantic/src/concept.rs, shared_crates/package_semantic/src/item.rs, shared_crates/package_semantic/src/lib.rs, shared_crates/package_semantic/src/message.rs, shared_crates/package_semantic/src/package.rs, shared_crates/package_semantic/src/scope.rs, shared_crates/package_semantic/src/type_.rs
Simplifying this code to allow removing the tokio Mutex in the ECS
=> Remove interior mutability from semantic

Cargo.lock, web/Cargo.lock
=> Update locked deps to make them match

crates/animation/src/player.rs
As proposed by @philpax here: https://github.com/AmbientRun/Ambient/issues/586
=> Use saturating sub in animation

crates/wasm/src/shared/module.rs, recipes.json
This improves the launch speed of games using multiple packages
=> feat: initialize wasm in parallel

app/src/cli/new_package.rs, app/src/cli/new_package_template/ambient.toml
@pierd @philpax Can you just verify this logic makes sense? (I just removed the production config and made it always use the not-production one)
Resolves #873
=> Fix new package api version. Fixes #873

crates/network/src/web/client.rs, web/client/src/app.rs, web/client/src/lib.rs, web/dioxus_example/src/main.rs, web/www/src/main.ts
Allows version mismatches on `www` and adds a `context` parameter to allow selecting another server
=> Fix web client local dev

app/src/cli/deploy.rs
Might have caused missing/wrong screenshots and README files uploads.
=> Fix package path in deployment

guest/rust/Cargo.lock, guest/rust/api_core/src/internal/generated.rs, shared_crates/package_macro_common/src/concepts.rs
Pretty straightforward, just running it through the CI "just in case"
=> feat(macro): make concepts partialeq

Cargo.lock, app/Cargo.toml, app/src/cli/package/deploy.rs
Just show the url that the user can click
=> Clean up deploy output

crates/ecs/src/component_registry.rs, crates/ecs/src/stream.rs, crates/network/src/diff_serialization.rs, crates/network/src/proto/client.rs, crates/network/src/proto/mod.rs, crates/network/src/proto/server.rs
Fixes: https://github.com/AmbientRun/Ambient/issues/927
=> Sync external components through diffs

Cargo.lock, crates/renderer/src/outlines.rs, guest/rust/packages/games/tictactoe/src/client.rs, guest/rust/packages/tools/editor/src/server.rs, web/Cargo.lock
This was caused by `RgbaF32` not being blendable according to the spec, but native vulkan being lenient
Fixes: #1004 Fixes: #888
=> Fix outline rendering

README.md
rendered: https://github.com/AmbientRun/Ambient/blob/cut-down-readme/README.md
=> docs(readme): simplify for 0.3

crates/app/src/lib.rs, crates/gpu/src/gpu.rs, crates/gpu/src/gpu_run.rs, crates/gpu/src/multi_buffer.rs, crates/gpu/src/texture.rs, crates/gpu_ecs/tests/gpu_ecs.rs, web/www/src/main.ts
=> Propagate gpu creation errors

guest/rust/Cargo.lock, guest/rust/Cargo.toml, guest/rust/examples/benchmarks/animations/Cargo.toml, guest/rust/examples/benchmarks/animations/ambient.toml, guest/rust/examples/benchmarks/animations/src/client.rs, guest/rust/packages/std/character_animation/src/client.rs, guest/rust/packages/tools/performance_bar/Cargo.toml, guest/rust/packages/tools/performance_bar/ambient.toml, guest/rust/packages/tools/performance_bar/src/client.rs
I removed the "fix" and just left the (very simple) benchmark; figured at least it would be useful as a basic benchmark for animations
=> Animations benchmark + performance bar

crates/build/src/lib.rs
Was running out of file descriptors
=> Add a write semaphore for asset builds

guest/rust/packages/schemas/unit/ambient.toml, guest/rust/packages/std/character_movement/ambient.toml, guest/rust/packages/std/character_movement/src/server.rs
(Mostly just need unit_displacement so I can debug why my character isn't moving, but added air speed multiplier as well)
=> Add air speed multiplier for character movement

crates/settings/src/lib.rs
Also, makes it a lot more clearer and less nested as clippy usually does
=> Satisfy clippy in ua parsing

.github/workflows/deploy-docs.yml, .github/workflows/release-version.yml
https://github.com/AmbientRun/Ambient/issues/1029
=> Add deploy docs action

crates/network/src/web/client.rs
... so it calculates from the beginning of the last frame to the beg of the current one. It's more exact when processing out of our task takes significant time.
=> Adjust frame dropping frame time calculation
